import fs from 'node:fs';
import assert from 'node:assert/strict';
const html=fs.readFileSync(new URL('../passaporte.html',import.meta.url),'utf8');
const js=fs.readFileSync(new URL('../platform.js',import.meta.url),'utf8');
assert(html.includes('<h1>Passaporte Digital VIRA</h1>'),'missing Passaporte h1');
assert((html.match(/DEMONSTRAÇÃO/g)||[]).length>=3,'demo label must be repeated');
for(const id of ['VIRA-PAVER-DEMO-0001','VIRA-BLOCO-DEMO-0001','VIRA-GUIA-DEMO-0001']) assert(html.includes(id),`missing ${id}`);
for(const family of ['paver','blocos','guias']) assert(html.includes(`data-passport="${family}"`),`missing ${family} tab`);
assert.equal((html.match(/data-passport-panel=/g)||[]).length,3,'three static panels required');
assert(js.includes('function initPassportDemo()'),'missing passport initializer');
console.log('passaporte: ok');
